version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgreSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment-service:
    build: .
    container_name: payment-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:3326/paymentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: postgreSQL
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9090:9090"
    restart: on-failure

volumes:
  postgres_data:
    driver: local